### Item id to reuse in tests
@item_id = 000000000000000000000000

### ---------------------------------------------------
### List all items
GET http://localhost:3000/api/items
Accept: application/json

### Create a new item
# @name create_item
POST http://localhost:3000/api/items
Content-Type: application/json
Accept: application/json

{
  "name": "Test Widget",
  "price": 42
}

### Capture id from last response
@item_id = {{create_item.response.body.$.data._id}}

### Get created item by ID
GET http://localhost:3000/api/items/{{item_id}}
Accept: application/json

### Update created item
PUT http://localhost:3000/api/items/{{item_id}}
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Widget",
  "price": 99
}

### Delete created item
DELETE http://localhost:3000/api/items/{{item_id}}
Accept: application/json

### Render Routes ---------------------------------------------------
### Item id to reuse in tests
@item_id = 000000000000000000000000

### ---------------------------------------------------
### List all items
GET https://web-services-final.onrender.com/api/items
Accept: application/json

### Create a new item
# @name create_item
POST https://web-services-final.onrender.com/api/items
Content-Type: application/json
Accept: application/json

{
  "name": "Test Widget",
  "price": 42
}

### Capture id from last response
@item_id = {{create_item.response.body.$.data._id}}

### Get created item by ID
GET https://web-services-final.onrender.com/api/items/{{item_id}}
Accept: application/json

### Update created item
PUT https://web-services-final.onrender.com/api/items/{{item_id}}
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Widget",
  "price": 99
}

### Delete created item
DELETE https://web-services-final.onrender.com/api/items/{{item_id}}
Accept: application/json